### ISSUE TITLE
Add support for mDNS candidates

### ISSUE THREAD

**Issue by jlaine** [aiortc/aioice#14]
Recent browser versions include candidates which do not specify an IP address but instead an mDNS host name. As a first step we should support receiving and using such candidates.

The problem is that using such candidates involves performing a DNS lookup, which is an asynchronous operation. This probably means our current API for providing remote candidates will need to be changed in a backwards-incompatible way:

- remove the setter for `remote_candidates`
- make `add_remote_candidate` a coroutine

**Comment by stalkerg** [comment]
Just post my workaround for this problem:
```python
    candidate = candidate_from_sdp(ice["candidate"].split(":", 1)[1])
    if ".local" in candidate.ip:
        logger.debug(f"Candidate contain mDNS -  resolve it {candidate.ip}")
        loop = asyncio.get_event_loop()
        try:
            result = await loop.getaddrinfo(candidate.ip, candidate.port)
        except socket.gaierror:
            logger.warning(f"Can't resolve host:{candidate.ip}")
            return
        candidate.ip = result[0][4][0]
        logger.debug(f"Result resolving {candidate.ip}")
        loop = asyncio.get_event_loop()
```

I hope you catch main idea. 
PS @jlaine probably you can integrate the same thing into aiortc
PS2 you should have avahi-daemon and properly configured nsswitch.conf with mDNS client.

**Comment by lgrahl** [comment]
If you resolve using the multicast addresses `224.0.0.251:5353` and `[ff02::fb]:5353` as the DNS server address there should not even be a need to have an avahi daemon running.

**Comment by jlaine** [comment]
If you're after a hack, here is one for aioice itself:

```diff --git a/src/aioice/ice.py b/src/aioice/ice.py
index d6cc328..7e493d9 100644
--- a/src/aioice/ice.py
+++ b/src/aioice/ice.py
@@ -107,6 +107,8 @@ def validate_remote_candidate(candidate: Candidate) -> Candidate:
     """
     if candidate.type not in ["host", "relay", "srflx"]:
         raise ValueError('Unexpected candidate type "%s"' % candidate.type)
+    if candidate.host.endswith(".local"):
+        candidate.host = socket.gethostbyname(candidate.host)
     ipaddress.ip_address(candidate.host)
     return candidate
 
```

However this unfortunately introduces a blocking call, which spoils the async fun..

**Comment by stalkerg** [comment]
> However this unfortunately introduces a blocking call, which spoils the async fun..

asyncio support async method for `getaddrinfo` (it use extra thread as I remember but still)

**Comment by stalkerg** [comment]
@lgrahl really? Will it be working even with the default dns client? Or I still need mdns-client in nsswitch.conf?

**Comment by lgrahl** [comment]
Yeah, it should work without a special client. Try it yourself: `drill @224.0.0.251 -p 5353 some-host-advertised-via-mdns.local`

**Comment by jlaine** [comment]
> asyncio support async method for `getaddrinfo` (it use extra thread as I remember but still)

Yes, an async version of getaddrinfo exists. The problem is that we are inside a synchronous function call, not a coroutine. To keep everything asynchronous would require a breaking API change: making `add_remote_candidate` a coroutine and removing the setter for `remote_candidates`

**Comment by stalkerg** [comment]
> To keep everything asynchronous would require a breaking API change: making add_remote_candidate a coroutine and removing the setter for remote_candidates

and it's a good reason for that. Or we can add extra asyncio api version and deprecate the current one.

**Comment by marksteward** [comment]
Happy to look at this if nobody else is. It might be possible to have `add_remote_candidate` do its work synchronously and leave processing the candidates for later?

**Comment by jlaine** [comment]
I've got PR #26  which removes the `remote_candidates` setter and makes `add_remote_candidates` a coroutine. The next step is to resolve mDNS candidates, but I'm not sure how to add tests for it.. how does one adverstise mDNS entries in a cross-platform manner?

**Comment by hidaris** [comment]
Any new developments? It seems that one after another mainstream browsers are using mdns

**Comment by stalkerg** [comment]
> I'm not sure how to add tests for it.. 

probably firstly we should implement it and after think about tests. Finally, we can just run docker with avahi for that. One OS will be enough for the start.

**Comment by richlegrand** [comment]
Hi everyone, 
Sorry for butting in --- I'm an enthusiastic and motivated but not very knowledgeable user of aiortc.  I want to use aiortc for our new product:
https://vizycam.com/  (Raspberry Pi-based vision system)
  
It works great for the most part.  I'm even able to use the Pi's accelerated encoder for a nice low-latency low-bitrate video stream.  

But I've noticed in the last year that chrome desktop is now using mdns exclusively.

I've played with adding gethostbyname to validate_remote_candidate, and it works.  I'm aware of the asyncio implications...  I did some experiments with running add_remote_candidate in an executor from addRemoteCandidate in rtcicetransport.py.  The right things seemed to happen, but the connection state didn't transition from checking to completed (maybe for reasons that are obvious to everyone except me.)

In my experiments, I sometimes receive two mDNS candidates, one which resolves successfully and one which fails after a lengthy timeout.  This can delay the connection by quite a bit.  I was thinking about reducing the timeout.... but I thought I'd just reach out and say hi first and see if anyone would like to give me some marching orders (?)  I could use some help, but maybe my efforts could be useful, too.  

thanks!

**Comment by stalkerg** [comment]
> In my experiments, I sometimes receive two mDNS candidates, one which resolves successfully and one which fails after a lengthy timeout. This can delay the connection by quite a bit. I was thinking about reducing the timeout.... but I thought I'd just reach out and say hi first and see if anyone would like to give me some marching orders (?) I could use some help, but maybe my efforts could be useful, too.

probably it should be separate issue... but this two candidates is it same?

**Comment by lgrahl** [comment]
It really shouldn't matter that mDNS is on when aiortc is talking to a browser that solely produces mDNS candidates. As long as the aiortc candidates are sent to the browser, peer reflection should kick in and the peer connection should be established.

**Comment by richlegrand** [comment]
I should have mentioned -- the goal is no STUN server for local connections.

**Comment by richlegrand** [comment]
The two mDNS candidates have to do with the 2 NICs on my system.  If it evaluated all of the candidates and parallel and went with the first answer, would that be correct behavior?

**Comment by richlegrand** [comment]
Anyway, I don't know if I'm making sense, or if this is a useful feature.  If anyone wants to help us implement along with other features, please send me a note (charmedlabs.com  (rich at))  This would be a paid gig.  Thanks!

**Comment by jlaine** [comment]
aioice 0.7.0 finally made `add_remote_candidate` a coroutine, so we now have a proper place to experiment with resolving mDNS candidates.

**Comment by jlaine** [comment]
There's a work-in-progress PR here: #36

**Comment by jlaine** [comment]
For the curious, here is what a bare-minimal mDNS resolver using asyncio might look like, leveraging dnspython to perform message parsing / serialization:

```python
import asyncio
import socket
from typing import Text, Tuple, Union, cast

import dns.message
import dns.name

MDNS_ADDRESS = "224.0.0.251"
MDNS_PORT = 5353


class MDnsProtocol(asyncio.DatagramProtocol):
    def __init__(self):
        self.queries = {}

    def connection_made(self, transport: asyncio.BaseTransport) -> None:
        self.transport = cast(asyncio.DatagramTransport, transport)

    def datagram_received(self, data: Union[bytes, Text], addr: Tuple) -> None:
        message = dns.message.from_wire(data)
        for answer in message.answer:
            for item in answer.items:
                if len(item.data) == 4:
                    future = self.queries.pop(answer.name, None)
                    if future is not None:
                        future.set_result(socket.inet_ntoa(item.data))

    async def resolve(self, hostname: str) -> None:
        name = dns.name.from_text(hostname)
        message = dns.message.make_query(name, "A")
        message.id = 0
        message.flags = 0

        future = asyncio.Future()
        self.queries[name] = future
        self.transport.sendto(message.to_wire(), (MDNS_ADDRESS, MDNS_PORT))
        return await future


async def create_mdns_resolver():
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.setsockopt(
        socket.IPPROTO_IP,
        socket.IP_ADD_MEMBERSHIP,
        socket.inet_aton(MDNS_ADDRESS) + b"\x00\x00\x00\x00",
    )
    sock.bind((MDNS_ADDRESS, MDNS_PORT))
    _, protocol = await loop.create_datagram_endpoint(
        lambda: MDnsProtocol(),
        sock=sock,
    )
    return protocol
```

It can then be used like so:

```python
resolver = await create_mdns_resolver()
answer = await resolver.resolve(hostname)
``

**Comment by jlaine** [comment]
.. and mDNS support has finally landed!
