### ISSUE TITLE
aioice using sip

### ISSUE THREAD

**Issue by PavelBerkut** [aiortc/aioice#18]
Good day! README says that the library allows you to use SIP, but I could not find any references in the source code. Could you explain to me whether it is possible to use SIP?

**Comment by lgrahl** [comment]
It's the other way 'round. SIP can use ICE.

**Comment by jlaine** [comment]
Yup @lgrahl nailed it: the README mentions SIP as a possible usecase for SIP, but that is outside the scope of this library.
