### ISSUE TITLE
Channel Binding

### ISSUE THREAD

**Issue by buendiya** [aiortc/aioice#29]
Hi
According to https://tools.ietf.org/html/rfc5766#page-14

> Channel bindings last for 10 minutes unless refreshed -- this
   lifetime was chosen to be longer than the permission lifetime.
   Channel bindings are refreshed by sending another ChannelBind request
   rebinding the channel to the peer.

I can't find the code about refreshing channel binding.

I am using coturn as turnserver. After 10 minutes coturn will output the log
> peer 172.17.0.1 deleted

and the peer will not receive data again.

**Comment by jlaine** [comment]
You seem to have a valid point here. There is code to refresh the allocation, but not channel bindings.
