### ISSUE TITLE
components more then 1 produce incorrect stun srflx

### ISSUE THREAD

**Issue by marakew** [aiortc/aioice#38]
subj

the issue at "get_component_candidates"
1)
there is need add local variable 
protocols = []
2)
replace at the body func "get_component_candidates" by protocols.append instead self._protocols.append
3)
and append it at end of "get_component_candidates"
self._protocols += protocols

hope you understand fix and there is no need push request

**Comment by jlaine** [comment]
OK yes I see what you mean, for each component we are collecting STUN addresses for every single component , which is not right.

**Comment by jlaine** [comment]
This is fixed in https://github.com/aiortc/aioice/commit/3b46994c638252b37637796c725e8630a1e7c1c2
