### ISSUE TITLE
Get nominated candidate pair and use in another application

### ISSUE THREAD

**Issue by siikamiika** [aiortc/aioice#49]
I would need to establish a UDP connection between two clients in an application, but the aioice API seems to only support sending data between the nominated pair through `send[to]` and `recv[from]`.

I was able to get the active pair by calling `<Connection>._nominated.get(1)` after reading the source, but `_nominated` is private so I don't think it's supposed to be used.

Is this something that's even supposed to be done using ICE or should I be using STUN directly?

**Comment by jlaine** [comment]
Hi! I'm not sure I understand, why would you want to run an ICE negotiation and then use a non-nominated pair?

**Comment by siikamiika** [comment]
Hi! My use case is connecting two WireGuard endpoints when they may be behind NAT and a stateful firewall. The original problem was already mostly solved by switching to IPv6 because my mobile carrier doesn't (yet) have a CGNAT for it like they do for IPv4.

> and then use a non-nominated pair

The goal was to get the nominated pair at that moment and then pass it to WireGuard, then retry in case the connection is lost. Wouldn't that be possible if the address/port were reused?

**Comment by jlaine** [comment]
Ouch, but aioice doesn't open the sockets in a way that allows the sockets to be reused, so it sounds like quite a hack anyway.. you might as well use the private attributes as I don't think the official API will cater to your usecase.

**Comment by siikamiika** [comment]
I see, thanks for the advice :+1:
