### ISSUE TITLE
Multiple early checks from same source results in unhandled tasks

### ISSUE THREAD

**Issue by ddiaz-yx** [aiortc/aioice#59]
Tested on version 0.7.6.

If multiple checks from a remote peer arrive before __check_list_ from _Connection_ class is set, then all of them are appended to the __early_checks_ list and then acted upon on the _connect_ method:
```
        # handle early checks
        for early_check in self._early_checks:
            self.check_incoming(*early_check)
        self._early_checks = []
```

Then the _check_incoming_ method creates a task for each early check and overwrites the handle for the associated pair:
```
            pair.handle = asyncio.ensure_future(self.check_start(pair))
```
Since the handle for some tasks is lost, they become unreachable and are not canceled after completion.

It is even possible to see mutiple times a transition `State.IN_PROGRESS -> State.IN_PROGRESS` for some candidate pairs.

**Comment by jlaine** [comment]
Sounds like a valid point, would you be ready to contribute a PR?

**Comment by eerimoq** [comment]
I noticed this as well. Any updates @ddiaz-yx ?

**Comment by eerimoq** [comment]
I implemented a PR that do not start a check if a check is already ongoing: https://github.com/aiortc/aioice/pull/68

**Comment by jlaine** [comment]
Fixed in https://github.com/aiortc/aioice/commit/54a575139b398a5d168512bc8c26b13d868068ce, thanks @eerimoq
