### ISSUE TITLE
netifaces is unmaintained

### ISSUE THREAD

**Issue by marksteward** [aiortc/aioice#62]
I can't use aiortc on 64-bit Windows because there's no wheel for netifaces and the project has been archived.

Happy to address this, but would it be better to fix netifaces or remove it as a dependency?

**Comment by jlaine** [comment]
Have you offered to (co)maintain netifaces, see https://github.com/al45tair/netifaces/issues/78 ?

**Comment by jlaine** [comment]
It looks like https://github.com/pydron/ifaddr is a good candidate, AFAICT it's Python-only so it does not require binary wheels.
